"""initial_migrate

Revision ID: 04f1db7f6aff
Revises: 
Create Date: 2025-05-22 23:14:34.946942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f1db7f6aff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mappings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('short_code', sa.String(length=10), nullable=False),
    sa.Column('long_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_url_mappings_short_code'), ['short_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_url_mappings_short_code'))

    op.drop_table('url_mappings')
    # ### end Alembic commands ###
